### ISSUE TITLE
Persistance recipe needed (expanded autossh note in documentation)

### ISSUE THREAD

**Issue by rsyncnet** [sshuttle/sshuttle#143]
The sshuttle documentation has a very brief note suggesting that 'autossh' is a good tool to use in conjunction with sshuttle.

After inspecting the autossh tool and looking at the actual ssh process that sshuttle creates on the client, it's not obvious to me that simply inserting autossh in place of the ssh command will create the desired results (ie., sshuttle reconnects upon a broken ssh connection).

Can someone simply expand that note in the documentation:

https://sshuttle.readthedocs.io/en/stable/requirements.html#additional-suggested-software

... with one or two additional sentences confirming exactly how one uses autossh in conjunction with sshuttle and what it actually achieves ?

I notice there are some outstanding email posts in the google group asking for this same clarification.

Many thanks.

**Comment by brianmay** [comment]
Pull requests appreciated :-)

**Comment by flashashen** [comment]
@rsyncnet, what did you find lacking with autossh?  

I rolled my own ([no-YOU-talk-to-the-hand](https://github.com/flashashen/no-YOU-talk-to-the-hand)) because i wanted more than it offered but it looked perfect for just keeping sshuttle connected.

**Comment by rsyncnet** [comment]
@flashashen - as I mentioned, it's not obvious what one is even supposed to do with authossh in relation to sshuttle ...

May I ask you - do you simply substitute the autossh command with a -e command line switch in sshuttle:

sshuttle -e 'autossh' ....

It seemed too easy ... is that all you are doing ?

**Comment by flashashen** [comment]
@rsyncnet - autossh just monitors and restarts the ssh process if needed. So sshuttle creates the autossh process which creates the ssh process and this would seem to achieve the 'desired result'. And, yes, the usage would be with '-e'. *HOWEVER*, after some testing it's apparent that this *can't work* since sshuttle sends server code for compilation after the ssh session is established. In this scenario sshuttle has no knowledge of the reconnect and it does not resend the server code. In my test, I killed the session on the remote, saw the new ssh connection, but I started seeing this error repeated in the terminal where i started sshuttle: 

```
TypeError: compile() expected string without null bytes
Traceback (most recent call last):
  File "<string>", line 1, in <module>
```

I don't think it's possible to reverse control and use autossh to restart sshuttle which is the only way it would work as I now understand it. 

I wonder if autossh was ever compatible with sshuttle

**Comment by rsyncnet** [comment]
As I said, it seemed too good to be true ... I would love to be proven wrong, however.

At the same time, I would also like to avoid adding the complication that daemonizing sshuttle would require ... in fact, I am inclined to do something very inelegant like set up key-based authentication (so I am not required to type in a password) and then chain together sshuttle commands:

sshuttle ; sshuttle ; sshuttle ; sshuttle

... so that even after three connection losses, I still have a working VPN ... this is of course, very ugly ...

**Comment by rsyncnet** [comment]
I'd like to suggest that the reference to autossh be removed from the documentation.

The consensus seems to be that it will not work as it suggests and that autossh is not relevant to sshuttle in any meaningful way.

**Comment by brianmay** [comment]
Pull requests welcome!

**Comment by dmitry-kulikov** [comment]
What about such approach?
```sh
sudo sh -c '
while :
do
    sshuttle --dns --remote username@sshserver 0/0
done'
```
Works for me. The only inconvenience is that the whole loop must be executed with sudo, as a result sshuttle will use /root/.ssh/, not /home/username/.ssh/.

**Comment by brianmay** [comment]
Closing this as I really don't have any good ways of running sshuttle interactively.

It is possible the answer given in https://github.com/sshuttle/sshuttle/issues/143#issuecomment-339188603 might be sufficient for some people however. I will accept pull requests to add this to the documentation.
