### ISSUE TITLE
Using without a network device

### ISSUE THREAD

**Issue by AshleighAdams** [sshuttle/sshuttle#152]
Is it possible to use sshuttle if I have no up network connections?  I am relaying the SSH connection over a USB cable (and listening for SSH connections on localhost).

I'm wondering if there's anyway to create a dummy network interface in which all the data will be forwarded to and sshuttle will pick up and forward it on.

**Comment by DanielO** [comment]
I haven't tried but you can probably create a tap or lo interface and bring it up, then route to it.
Then sshuttle will intercept those packets and DTRT.

**Comment by brianmay** [comment]
Not sure there is anything to do here. sshuttle should work wherever you can create a ssh connection. Will close. If there is any specific requirements for sshuttle, please say so and I will reopen.

**Comment by normanr** [comment]
ssh doesn't necessarily require a default route, it can also connect via:
 * a local proxy server, because the network has no default route to the internet, and requires that all outgoing connections should be made via the proxy,
 * a port forwarded with adb to a USB connected phone (or reverse Wi-Fi hotspot)

I worked around this by making a script that creates a tun interface, sets it up, and adds the required route(s) to it. (and any packets sent out the interface are just dropped until sshuttle registers its redirects.) It would be nice if sshuttle would do this as part of its firewall manager.

**Comment by grepsuzette** [comment]
@normanr Are you still using that script? 

I am trying to do reverse tethering with https://github.com/Genymobile/gnirehtet connecting to my host running sshuttle, but it does not route anything. As soon as I close sshuttle it will work normally.

**Comment by normanr** [comment]
Unfortunately not. I now have a mobile plan that allows tethering, so I have not needed to use sshuttle since.
