### ISSUE TITLE
only forwarding dns for the remote subnet

### ISSUE THREAD

**Issue by brianjmurrell** [sshuttle/sshuttle#153]
As I understand it, the `--dns` option forwards **all** DNS requests to the remote subnet's DNS servers, yes?  If so, that only works as long as the remote DNS server(s) know about everything that is local to you also.

If it doesn't however, and if I wanted to forward only DNS requests for the domain that is on the remote subnet I could adjust my current BIND configuration (my `/etc/resolv.conf` lists 127.0.0.1 as the DNS server to use) to add something like:

```
zone "remote.domain.example.com" IN {
	type forward;
	forwarders port 12303 { 127.0.0.1; };
};
```

Where sshuttle is listening on port 12303 on the localhost for DNS requests to proxy to the remote subnet.

Give that, is there was a way to start sshuttle so that it forwarded DNS requests received on a port but didn't capture all DNS requests so that DNS requests for the remote subnet/domain could be specifically directed by the local BIND daemon?

**Comment by brianjmurrell** [comment]
Through some experimentation I have discovered that if I start sshuttle with `sshuttle -l 12303 --dns -Nvvvr me@remote_host.example.com` and then `sudo iptables -t nat -D sshuttle-12303 4` and add the following to my BIND configuration:

```
zone "remote.domain.example.com" IN {
	type forward;
	forwarders port 12300 { 127.0.0.1; };
};

```

I get the behaviour I am desiring.

But is there a more straightforward way of starting sshuttle so that it works this way?

Why is the DNS proxy on port 12300?  What if I wanted to start several sshuttles each with their own DNS proxy on it's own port?

**Comment by brianmay** [comment]
Years ago I created an experimental branch for fixing this type of issue. It allowed filtering of DNS requests based on the domain name. I can't remember what the use case was. The patch never got merged, and probably needs work to ensure it merges correctly and it works.

Hmmm. Wonder if it is still available. Oh, this looks like it:
https://github.com/apenwarr/sshuttle/compare/master...brianmay:dns

**Comment by brianjmurrell** [comment]
> Years ago I created an experimental branch for fixing this type of issue

But it wouldn't work where there were multiple sshuttle tunnels configured would it?

**Comment by vieira** [comment]
Hello @brianjmurrell,

It is possible to only forward some queries to the remote DNS servers. To do so in addition to adding the zone to bind like you did and forwarding to the remote DNS servers (instead of localhost) you should also use the --ns-hosts flag with the remote DNS servers and sshuttle will capture and tunnel the requests made to those servers.

It is also possible to simply use dnsmasq instead of bind, see http://www.vojcik.net/configure-different-dns-resolvers-for-domains-in-ubuntu/

**Comment by brianjmurrell** [comment]
> also use the --ns-hosts flag

Isn't `--ns-hosts` just explicitly specifying the remote DNS servers rather than letting sshuttle figure them out automatically -- but still with the same behaviour of forwarding *all* DNS requests to the remote server(s)?  This debian bug reporting [message](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=822864#29) posting by @brianmay seems to indicate so:

> I suggest you may not need to give the name servers, just use --dns option by itself. sshuttle
will work out the DNS servers automatically.

Maybe I am not quite understanding what that flag is supposed to be for.  The description is rather nebulous:

_ns-hosts=  capture and forward remote DNS requests to the following servers_

Is it really just remote DNS requests?  How does sshuttle know which DNS requests are remote and which ones are not?

> It is also possible to simply use dnsmasq instead of bind

Indeed.  As I mentioned in my PR for this:
> Of course, this is not specific to BIND. This could be used with any "smart" DNS resolver that is able to forward DNS requests to a DNS server on a given host:port tuple

**Comment by vieira** [comment]
@brianjmurrell While --dns tunels all DNS requests, --ns-hosts only tunels DNS requests going out to the specified servers.

Let's say example.com is a domain resolving in your remote network and 192.168.100.254 is the DNS server of your remote network.

```
zone "example.com" IN {
	type forward;
	forwarders port 12300 { 192.168.100.254; };
};
```

Launching sshuttle with 
```
$ sshuttle -r user@server --ns-hosts=192.168.100.254
```
will tunel DNS requests of *.example.com via sshuttle and let others resolve normally.

**Comment by brianjmurrell** [comment]
> --ns-hosts only tunels DNS requests going out to the specified servers

But it does mean I need to know (and keep up with changes to) the IP addresses of the remote nameservers.

My [PR](https://github.com/sshuttle/sshuttle/issues/154) on the other hand preserves the automatic detection of the remote nameservers but limits use of them to only resolving the remote domain over the tunnel.

**Comment by vieira** [comment]
@brianjmurrell no, you don't. You can use 127.0.0.1 (or anything else) as in your example. As long as the address you specify in sshuttle is the same to where you forward it should work even if that DNS server does not exist.

```
zone "example.com" IN {
	type forward;
	forwarders { 127.0.0.1; };
};
```
and run sshuttle with
```
$ sshuttle -r user@server --ns-hosts=127.0.0.1
```

**Comment by brianjmurrell** [comment]
It doesn't seem to work here as you advertise.

I cannot see how it could.

If I have BIND running on 127.0.0.1:53 and I have sshuttle's DNS proxy on 127.0.0.1:12302 and using `--ns-hosts` results in an iptables rule as such:

```
Chain sshuttle-12303 (2 references)
 pkts bytes target     prot opt in     out     source               destination         
...
  568 44699 REDIRECT   udp  --  *      *       0.0.0.0/0            127.0.0.1            udp dpt:53 TTL match TTL != 42 redir ports 12303
```
**all** DNS requests are going to sshuttle.  How does sshuttle then know what to send to the remote DNS servers and what to send elsewhere, and where elsewhere is?

**Comment by vieira** [comment]
@brianjmurrell If you have bind running locally and listening on 127.0.0.1 change the rule to something else like:

```
zone "example.com" IN {
	type forward;
	forwarders { 127.10.0.1; };
};
```
and run sshuttle with
```
$ sshuttle -r user@server --ns-hosts=127.10.0.1 ...
```
I have just tested on my machine and it works as expected. For anyone using dnsmasq and looking at this in the future, say you want to tunel dns requests via sshuttle for domain `reddit.com` only:

```
$ cat /etc/NetworkManager/dnsmasq.d/custom-dns 
server=/reddit.com/127.10.0.1
```
and I ran sshuttle with:
```
$ sshuttle -r user@myserver --ns-hosts=127.10.0.1 ...
```

**Comment by brianjmurrell** [comment]
Ahh.  Now I am seeing the difference in what I was [mis-]understanding what you were trying to say.

It does seem to work as you describe.  Cool.

**Comment by brianmay** [comment]
Has this been resolved? Can I close this ticket?

**Comment by iramello** [comment]
Hi,
Two simultaneous tunnels running at the same time:

1) sshuttle -v --ns-hosts=172.30.0.2 -r <host1> 172.30.0.0/16
2) sshuttle -v --ns-hosts=10.3.0.2 -r <host2> 10.3.0.0/16

when I execute
dig <subdomain-in-1> @172.30.0.2, it works
and
dig <subdomain-in-2> @10.3.0.2, it does NOT work because the query is sent through the first tunnel (viewable by -v)

Please let me know if you need any other information, but at first sight it looks like the DNS forwarder for sshuttle is always started using the same UDP port ( "message DNS listening on ('127.0.0.1', 12300)." ), and is always sent to the same tunnel.

sudo netstat -anp|grep :12300
tcp        0      0 127.0.0.1:12300         0.0.0.0:*               LISTEN      30155/python3
udp        0      0 127.0.0.1:12300         0.0.0.0:*                           30187/python3
udp        0      0 127.0.0.1:12300         0.0.0.0:*                           30155/python3

**Comment by iramello** [comment]
@brianmay A possible fix is not to set SO_REUSEADDR for the socket (not sure why it is being set before calling the bind function, both v4 and v6).  
https://github.com/apenwarr/sshuttle/blob/083293ea0dc2ebc77f282c2803720a2bb5f21a80/sshuttle/client.py#L152
I confirm that setting it to 0 instead of 1 on the line above (i.e. using different ports for UDP) works as expected and queries are routed to the proper tunnel.
Please suggest how I should proceed? PR or what?

**Comment by brianmay** [comment]
My understanding is that the kernel should disallow to sockets to bind to the same port at the same time, even if `SO_REUSEADDR` is set. So I don't know what is happening here.

I believe `SO_REUSEADDR` just means you can reuse the same ip/port immediately after the program has exited.Which shouldn't be the case here. See https://stackoverflow.com/questions/3229860/what-is-the-meaning-of-so-reuseaddr-setsockopt-option-linux

**Comment by brianmay** [comment]
Oops, that was for TCP, not UDP. For UDP see: https://stackoverflow.com/questions/577885/uses-of-so-reuseaddr

Looks like you are right, we shouldn't be using it for UDP sockets.

**Comment by iramello** [comment]
Sent! Thanks

**Comment by brianmay** [comment]
I think this might be fixed now. Closing.
