### ISSUE TITLE
Source IP address not the Remote Server

### ISSUE THREAD

**Issue by jmcgrath207** [sshuttle/sshuttle#229]
When I send traffic to a server on the remote network, It is using the source IP address of my local machine instead of the the remote server I am connecting too. How would I make it so traffic appears it coming from the remote server I am connected too?

**Comment by brianmay** [comment]
John McGrath <notifications@github.com> writes:

> When I send traffic to a server on the remote network, It is using the
> source IP address of my local machine instead of the the remote server
> I am connecting too. How would I make it so traffic appears it coming
> from the remote server I am connected too?

It sounds like sshuttle may not be intercepting the packets you expect
it to.
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by jmcgrath207** [comment]
Thanks for taking a look at this @brianmay 

The tunneling part of it still works correctly just the source IP address is not changing.

Here is the command that I am using `sshuttle -HNvr  remoteUser@remoteServer` and I am using version `0.78.4`

**Comment by brianmay** [comment]
Maybe I haven't understood you situation. However, if sshuttle works, all connections through sshuttle will use the IP address on the remote sshuttle server. This is a mandatory requirement. If you are getting a different IP address, the only way this is possible is if sshuttle is not intercepting the packets.

**Comment by brianmay** [comment]
John McGrath <notifications@github.com> writes:

> The tunneling part of it still works correctly just the source IP address is not changing.
>
> Here is the command that I am using `sshuttle -HNvr  remoteUser@remoteServer` and I am using version `0.78.4`

As you have not supplied any subnets, this will only forward
autodetected hosts (-H) and autodetected networks (-N). It may not be
forwarding to the hosts you want it to. Are you sure this is what you
want?
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by jmcgrath207** [comment]
So if I understand this correctly, `autodetected networks (-N)` and `autodetected hosts (-H)` will auto create a tunnel and forward the traffic but will not change the source IP address of my traffic. If I were to apppend `subnets` ex. `sshuttle subnets example.com:8000-9000 -HNvr remoteUser@remoteServer` This would allow sshuttle to change the source IP address for only example.com and forward the rests of the traffic without changing the Source Ip address.

Just a thought do you think if I forced it to use tproxy it would fixed this issue.

**Comment by brianmay** [comment]
John McGrath <notifications@github.com> writes:

> So if I understand this correctly, `autodetected networks (-N)` and
> `autodetected hosts (-H)` will auto create a tunnel and forward the
> traffic but will not change the source IP address of my traffic. If I
> were to apppend `subnets` ex. `sshuttle subnets example.com:8000-9000
> -HNvr remoteUser@remoteServer` This would allow sshuttle to change the
> source IP address for only example.com and forward the rests of the
> traffic without changing the Source Ip address.

No, not sure you understand yet.

For ALL traffic forwarded through sshuttle, the TCP connection will
origingate from the sshuttle server. This means all TCP connections will
have the source IP address of the sshuttle server.

If the IP address is not being changed, this is a sure sign that
sshuttle is not forwarding the traffic. As sshuttle operates at the
application network layer it simply is not capable of forwarding to a
TCP connection without changing the IP address.

When using -N and -H, sshuttle will attempt to automatically detect what
traffic to forward. Based on magic I haven't really investigated. As a
result, it may not be forwarding the traffic you expect it to be
forwarding. Neither -N nor -H correspond to "forward all traffic".

In general it is much better to specificy the subnets you want
forwarded, rather then relying on sshuttle to do something
automatically, because this automatic use case probably won't suit your
needs.

Does this help clarify?
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by brianmay** [comment]
No response, closing.
