### ISSUE TITLE
Buffer sizes should be configurable

### ISSUE THREAD

**Issue by kwilczek** [sshuttle/sshuttle#297]
Hi,

I noticed that (I don't want to use `--no-latency-control` because it basically destroys other connections)
for some reason my speed limit when using `sshuttle` (great project :+1: ) I reach a plateau about
~1-1,5 MB/s. This limit does not depend on my network capabilities (symmetric 1 Gbps) or a CPU of any of the tunnel sides. I started to trace the code starting from the keyword `latency` and got to these lines:

https://github.com/sshuttle/sshuttle/blob/d43db80decebce2d3e072f3b0a6acb9d0f71d523/sshuttle/ssnet.py#L368-L372

https://github.com/sshuttle/sshuttle/blob/d43db80decebce2d3e072f3b0a6acb9d0f71d523/sshuttle/ssnet.py#L446-L457

I increased the hardcoded limit twice and my throughput basically doubled :) Could you tell if changing these values from `32768` to basically anything else can have any side effects? I currently set this to `65535` and went from ~1MB/s to ~2 MB/s.

I also noticed that initial speeds tends to drop after some time to about 1 MB/s. Does someone know why?

Edit: on my other PC I changed it and the speed tripled initially.

Best Regards
Kamil

**Comment by brianmay** [comment]
See #272.

Doubling the buffers will obviously increase memory consumption, and optimal values will vary depending on how you are using sshuttle.

As such, this value should be configurable. However implementing a way to configure it in a non-hackish way might be interesting, as this code is deeply nested code, and has no direct access to command line parameters.

Patches welcome :-)

**Comment by kjaval** [comment]
I had the same limited speed for a while and was looking for a solution.
Finally I reached this page and it solved my problem.
I decided to increase by 2000 times the limit value mentioned here and as a result the limit increased 2000 times too which was wonderful!

I hope this can become configurable in the near future

**Comment by Belval** [comment]
@brianmay any ideas on how we could make this configurable? The code itself is indeed nested deeply and adding it as a parameter so `SockWrapper` seems improper. 

Could we pass it as an environment var? I suppose it could also be a commandline argument that sets the environ var, but that doesn't seem right either.

**Comment by brianmay** [comment]
These are very good questions. Unfortunately I can't answer them, nor do I have time to investigate right now.

**Comment by drjbarker** [comment]
@brianmay Is there a good reason not to do this in the same way as `ssnet.MAX_CHANNEL` is set?

The other options is to propagate the argument which is quite clean for `check_fullness()` but starts getting very messy for `fill()`.

I've  implemented the former and can send a pull request, but if you think that's too hackish then I  can spend some time on the later.

**Comment by normanr** [comment]
It would probably be better if the buffer sizes auto-tuned themselves:

For the read buffer: if the number of bytes read is equal to the buffer size, then double(?) the buffer size (for the next read), if the number of bytes read is less than a quarter of the buffer size then half the buffer size (probably with limits applied, and maybe with a decaying delay so that the read buffer doesn't shrink too quickly).

For the write buffer: the ping trigger and too_full limits should be separate. Then the ping could be sent before the buffer is too full, so that writes don't stall waiting for the ping. The buffer size needs to be recorded when sending the ping, so that fullness can be reduced by that amount instead of setting it to zero. There could also be multiple pings in flight at the same time. (I'd guess that this would have the biggest impact on sending rate, because today sends stall while the ping is in flight).

The send buffer size could also change dynamically, but I'm not sure what the best signals are. There are plenty of TCP congestion control algorithms out there, and sshuttle could use one that only depends on measurement of delay (like Vegas or BBR). Recording the time at which the ping packets are sent would be required to calculate the delay.

**Comment by drjbarker** [comment]
@normanr Interesting! I had thought about trying to measure the RTT for the ping but hadn't though much about what to do after that. Implementing Vegas sounds sensible.

Do you have the time/inclination to give it a try or shall I have a look when I have some time?

**Comment by normanr** [comment]
I'm unlikely to have time to look at implementing anything so please take a look at it if you do. I think it would be interesting to do a baseline test of (up-only/down-only/up-and-down), and then try changing each parameter individually to see what makes the most difference.

I suspect that allowing multiple in-flight pings may actually be the biggest winner because it seems (from my brief reading of the code) that currently no other data can be sent while a ping is in flight. Tuning the rate of pings (bytes between pings) will reduce overhead make the transmission more efficient, but I suspect that will only help once the connection bandwidth is saturated (compared with the other changes which will help fill the connection to start with).

**Comment by brianmay** [comment]
Of course, even though I merged (and closed this), I am still open to pull requests that improve on this.

**Comment by ferfebles** [comment]
Could you ship a new release with this patch included, please?

**Comment by brianmay** [comment]
I am somewhat reluctant to make a new release while #381 is still open...This bug means sshuttle is unusable in Debian testing for example.

**Comment by normanr** [comment]
Does the current release work in Debian testing?

**Comment by brianmay** [comment]
I haven't tested testing, but I believe the answer is No. It might be possible to work around this by forcing python2, but that fix would never get accepted for Debian as they are phasing out use of python2.

**Comment by brianmay** [comment]
Anyway, such disucssions really belong with #381

**Comment by skuhl** [comment]
@normanr I've worked on this a bit (fixing the fact that no data can be sent when a ping is in flight). I wash surprised to discover that this is what sshuttle was doing!  I have a version where sent data has sequence numbers and the recipient acknowledges them with an ACK packet---so the sender can determine how much data is in flight without having to send a ping, stop sending, and wait for a response. I haven't found significant performance improvements with the change. However, it does make it possible to more frequently estimate what the round-trip time is. I'm looking at automatically and dynamically changing the buffer size so that sshuttle defaults to an appropriately sized buffer that has good bandwidth performance and good latency performance.

I also made pull request #587 which makes the latency buffer the same on both the client and the server if the size is specified on the command line.
