### ISSUE TITLE
proxy connections to a hostname instead of IP?

### ISSUE THREAD

**Issue by perfecto25** [sshuttle/sshuttle#348]
Hello, is it possible to proxy connections to a specific hostname instead of IP, ie

server A> sshuttle -r serverB www.somesite.com

if I want all connections to somesite.com to go via B, is it possible to route using a hostname, instead of using the site's IP (which can change)?

Thank you, love this application.

**Comment by perfecto25** [comment]
nevermind, theres a enhancement request open for this, Ill see if I have some cycles to add a PR

**Comment by skuhl** [comment]
This has been supported for some time, but it only forwarded the first of potentially many IPs that the host name resolves to. Pull request #541 changes the behavior so that all of the IPs that the host name resolves to are forwarded. 

This doesn’t regularly check to see if the IPs for the host name changes, however. So, whatever IPs the host name resolves to when sshuttle starts would be forwarded.
