### ISSUE TITLE
sshuttle requires netstat application in net-tools package to be installed on the host

### ISSUE THREAD

**Issue by cnicksic** [sshuttle/sshuttle#556]
Sshuttle mysteriously did not work when we tried using a new Linux host server from the same Linux remote server.  After quite a bit of effort the extremely simple solution was that the net-tools package must be installed on the host.  Here are the details.

First we tried with Python 2.7 installed on the host:

```
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
c : fatal: expected server init string b'SSHUTTLE0001'; got b''
```

That's not a helpful error message!  Someone suggested trying to install python3 which we did.  It still didn't work but thankfully it returned a far more helpful error message:

```
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'netstat': 'netstat'
c : fatal: expected server init string b'SSHUTTLE0001'; got b''
```

We quickly learned that netstat is part of the net-tools package, installed net-tools on the host, and sshuttle worked perfectly with both Python 2.7 and Python 3.6.  Hooray!

**Comment by skuhl** [comment]
Are you using --auto-nets with sshuttle? I believe that is the only time that the server looks for the 'ip' and the 'netstat' commands.

A pull request I submitted a while back should fix this. See #551 . With that patch, everything continues to work when both 'ip' and 'netstat' are missing *except* that --auto-nets will fail to work. When this occurs a warning will be printed explaining this.

If you have the ip command and wonder why that isn't working either, it is likely because sshuttle didn't look for 'ip' in all the paths that it could and it didn't reliably look in all the same paths at different places in the code. The pull request mentioned above should fix that too.

**Comment by cnicksic** [comment]
Thanks Scott!  I'm no expert on this topic but our expert told me after I posted this that the PR that you referenced did indeed fix this issue by returning a clear error message that netstat/net-tools was missing.  So I'm confident that this issue is fully resolved.  I just wanted to post this message in case others saw this issue too.

**Comment by dlenski** [comment]
> Thanks Scott! I'm no expert on this topic but our expert told me after I posted this that the PR that you referenced did indeed fix this issue by returning a clear error message that netstat/net-tools was missing. So I'm confident that this issue is fully resolved. I just wanted to post this message in case others saw this issue too.

I believe I am the “expert” in question :stuck_out_tongue_closed_eyes: 

The immediate issue — lack of clarity about the requirement for `netstat` — was in fact fixed back in https://github.com/sshuttle/sshuttle/commit/809fad537fa6977da3e3915f5a125e2a3d163254.

@cnicksic is using **v0.76** due to a frequent need to connect to ancient CentOS/RHEL 6-7 systems which only have Python 2.7 or even 2.6 (:panda_face:) available. I suspect that there may be a decent number of other users in similar situations who unfortunately cannot upgrade to sshuttle 1.0+ due to the requirement for Python 3.5 on the remote end. A very reasonable requirement, but unfortunately there are plenty of these ancient systems out there.

**Comment by skuhl** [comment]
Although it isn't officially noted in the documentation, don't the latest versions work with Python 2.7 on the remote host? It works for me. The Python 3.5 is required for the client/local machine and some support for older versions of python on the remote host was added back in after being removed.

**Comment by dlenski** [comment]
> Although it isn't officially noted in the documentation, don't the latest versions work with Python 2.7 on the remote host? It works for me. The Python 3.5 is required for the client/local machine and some support for older versions of python on the remote host was added back in after being removed.

Ah, thank you. [The changelog](https://sshuttle.readthedocs.io/en/stable/changes.html#id8) shows that support for Python 2.6/2.7 (as remote) was removed in v1.0. Would be good to document if it's been added back.
