### ISSUE TITLE
Google Chrome and other browsers leak IP to Facebook and Google search (except Firefox)

### ISSUE THREAD

**Issue by wirespecter** [sshuttle/sshuttle#574]
Hi there,

First of all, let me say thanks for this wonderful program! Currently I'm using version `1.0.5.dev69`.
I have a question about something that I can not explain...

If you do a `sudo sshuttle --dns -r USERNAME@SERVER -x SERVER_IP 0/0`
and then you launch google chrome and type "what is my ip" google search is showing the real IP! I have no idea how.
This happens in Facebook as well, but if you visit any other site is will not reveal the real IP.

I have disabled IPv6 and WebRTC so it can't be anything of those
I have also checked for DNS leaks, not this one either

If I do the same thing in firefox (visiting google & facebook) then google search doesn't show the real IP (as it should be).
I think that the firewall rules that sshuttle creates do not intercept calls to Google (and Facebook) from other browsers for some reason.

Same thing happens with Opera, Chromium and Brave browser

**Comment by skuhl** [comment]
Methods have varying support for UDP traffic (used by some browsers on some sites that support HTTP/3) and IPv6 traffic (may be used by your machine and remote sites). Some sshuttle "methods" do not support redirecting UDP or IPv6. Which "method" are you using?  Running with "-v" should show you. The "--method" parameter will let you select a different one.

Another issue might be that you may have to restart your browser after starting sshuttle since your browser might reuse connections that sshuttle didn't redirect that were started before sshuttle started. But, I imagine you've probably tried that since you are trying different browsers.

If you use a method that supports more UDP and/or IPv6 (whatever the problem is here), then I expect that things would work as you expect. For example, see https://sshuttle.readthedocs.io/en/stable/tproxy.html

This is what various methods support (for the current git version): https://github.com/sshuttle/sshuttle/blob/master/docs/requirements.rst

**Comment by wirespecter** [comment]
Thank you so much for your answer @skuhl 
I'm using the default method (which is "nat" if I'm not mistaken).

IPv6 is not used at all because I have disabled it in my system. Regarding UDP, if you visit google search with the browser, only TCP isn't taking place? (correct me if I'm wrong) I haven't seen any websites that can find the IP address by using UDP so far...

I have already restarted the browsers and cleared the cookies and cache as you indicated.

However, I would like to try the "tproxy" method in order to verify that UDP is not the problem.
I have followed the docs but I didn't manage to make it work (sshuttle was crashing I think, I can provide some logs if you wish).

Could you please provide me with an example? How do you use the "trpoxy" method? (I'm using Ubuntu Focal Fossa by the way). Also, could you please try to reproduce what I am describing in my first post? Do browsers behave the same way in other people as well? Thanks :)

**Comment by skuhl** [comment]
Yes, some browsers and websites have switched to HTTP/3 which use UDP instead of TCP for communication. In addition, Chrome used an earlier version of this (QUIC) which also uses UDP instead of TCP. For example see this post from 2018, which says "If you’re reading this in Chrome, you’re probably using QUIC right now": https://cloud.google.com/blog/products/gcp/introducing-quic-support-https-load-balancing

I'm not particularly interested in what browsers do. I care mostly if sshuttle is behaving as it should.  It isn't clear to me that there is a sshuttle bug here from what you describe. The method you were using didn't redirect UDP, some browsers use UDP (with some sites), and some browsers traffic wasn't redirected through sshuttle (on some sites). It seems safe to assume that the problem is using a method that doesn't support UDP.

Documenting what browsers do is challenging because they are a moving target. It seems outside the scope of sshuttle.

I don't have time to install more browsers and reproduce the problem. Maybe someone else can? The tproxy method works as expected for me (i.e., TCP and UDP gets redirected). Remembering to use the proper excludes as described in the article linked above is important. I agree the documentation could be improved and it isn't easy to set up.

If sshuttle is crashing, I'd suggest submitting the log as a separate issue.

**Comment by wirespecter** [comment]
Indeed! I verified just now that Chrome is using HTTP/3 which uses UDP! I had no idea... Thanks a lot for letting me know :)
Closing this issue now...
