### ISSUE TITLE
Sshuttle Documentation

### ISSUE THREAD

**Issue by naclander** [sshuttle/sshuttle#60]
Looking at the [original repository](https://github.com/apenwarr/sshuttle/tree/master/Documentation) for sshuttle I see there is a documentation folder with the man page. I could not find the commit that originally removed this folder.

The current man page on my system for sshuttle is very out of date (version 0.46), and I wanted to see if there was interest in adding a man page back to sshuttle to help package maintainers.

**Comment by brianmay** [comment]
The only documentation in that folder I think was the man page. With a lot of ``*.do`` files; I am not really sure what these are.

The ``sshuttle.md`` file now lives (rightly or wrongly) in the ``sshuttle`` directory:
https://github.com/sshuttle/sshuttle/blob/master/sshuttle/sshuttle.md

At the moment the version number is hard coded in ``sshuttle.md`` which is far from idea, because I forget to update it for new releases.

``sshuttle.md`` has been forgotten and is missing a lot of the recent changes - ipv6 support and UDP support come to mind.

Maybe some of the documentation from ``README.rst`` should go into ``ssshuttle.md``?

**Comment by naclander** [comment]
The .do files generate the man page from the sshuttle.md file. It looks like we no longer have a makefile, but another system could be created where an automatic man page would be generated with the correct version.

It seems like keeping a separate man page is a bit tedious, as a lot of information is shared from the readme. Listing some possible options:
* Write readme.rst in the same style as the man page, and then have some sort of rst->man page format converter
* Have a man page generator that would copy certain components from the readme.rst and add its own sections ("See Also", "Authors", etc.)
* Keep both the man page and readme up to date simultaneously. 

I have to think a bit more about the path that's most maintainable, but I definitely think its important we have an up to date man page, in a location that's easily identifiable to anyone who chooses to package sshuttle. Thoughts?

**Comment by brianmay** [comment]
Maybe an overkill - however Sphinx supports turning RST files into man pages. Have done it for another project.

This would help with keeping the version number correct; It would also mean that we are using the same format as README.rst which would be good too. Not sure it would help keeping the man page in sync with README.rst.

**Comment by brianmay** [comment]
Have moved documentation to Sphinx. Can generate man page, however I haven't updated the contents yet. Tried to get it to build sphinx documentation on readthedocs, but it fails to build at the moment, I think this might be an Sphinx bug that is fixed in git. https://readthedocs.org/projects/sshuttle/builds/3645106/

**Comment by brianmay** [comment]
Ok, documentation now available at http://sshuttle.readthedocs.org/en/latest/ - I had to remove the table in the requirements section due to Sphinx bug. Next step update to man page.
