### ISSUE TITLE
PermissionError: [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by yermulnik** [sshuttle/sshuttle#664]
On my new Ubuntu 20.04 laptop when I run `sshuttle` it errors out with `PermissionError: [Errno 1] Operation not permitted` message which I have never saw before on my previous laptop on Ubuntu 16.04. Tried installing `sshuttle` both using `apt` (`0.78.5`) and `homebrew` (`1.0.5`). Any clue?

Brew:
```
> sshuttle -r myjumphost mytgt
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/sshuttle", line 33, in <module>
    sys.exit(load_entry_point('sshuttle==1.0.5', 'console_scripts', 'sshuttle')())
  File "/home/linuxbrew/.linuxbrew/Cellar/sshuttle/1.0.5/libexec/lib/python3.9/site-packages/sshuttle/cmdline.py", line 46, in main
    return firewall.main(opt.method, opt.syslog)
  File "/home/linuxbrew/.linuxbrew/Cellar/sshuttle/1.0.5/libexec/lib/python3.9/site-packages/sshuttle/firewall.py", line 102, in main
    stdin, stdout = setup_daemon()
  File "/home/linuxbrew/.linuxbrew/Cellar/sshuttle/1.0.5/libexec/lib/python3.9/site-packages/sshuttle/firewall.py", line 73, in setup_daemon
    os.setsid()
PermissionError: [Errno 1] Operation not permitted
c : fatal: ['/bin/sudo', '-p', '[local sudo] Password: ', '/usr/bin/env', 'PYTHONPATH=/home/linuxbrew/.linuxbrew/Cellar/sshuttle/1.0.5/libexec/lib/python3.9/site-packages', '/home/linuxbrew/.linuxbrew/Cellar/sshuttle/1.0.5/libexec/bin/python', '/home/linuxbrew/.linuxbrew/bin/sshuttle', '--method', 'auto', '--firewall'] returned 1
```

APT:
```
> sshuttle -r myjumphost mytgt
Traceback (most recent call last):
  File "/bin/sshuttle", line 11, in <module>
    load_entry_point('sshuttle==0.78.5', 'console_scripts', 'sshuttle')()
  File "/usr/lib/python3/dist-packages/sshuttle/cmdline.py", line 26, in main
    return firewall.main(opt.method, opt.syslog)
  File "/usr/lib/python3/dist-packages/sshuttle/firewall.py", line 97, in main
    stdin, stdout = setup_daemon()
  File "/usr/lib/python3/dist-packages/sshuttle/firewall.py", line 68, in setup_daemon
    os.setsid()
PermissionError: [Errno 1] Operation not permitted
fatal: ['sudo', '-p', '[local sudo] Password: ', '/usr/bin/env', 'PYTHONPATH=/usr/lib/python3/dist-packages', '/usr/bin/python3', '/bin/sshuttle', '--method', 'auto', '--firewall'] returned 1
```

**Comment by skuhl** [comment]
Are you running sshuttle with --daemon or -D ?  It looks like it is trying to run as a daemon but that isn't in the arguments you specify. Does running with -vvv provide any other insights?

**Comment by yermulnik** [comment]
@skuhl I've switched to `sshuttle` from Homebrew rather than from APT since then (Brew has more recent version of `sshuttle`) but it's still the same error:
```
> sshuttle -vvv -r myjumphost.***************.com 172.26.0.0/16
Starting sshuttle proxy (version 1.0.5).
c : which() found 'sudo' at /bin/sudo
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/sshuttle", line 33, in <module>
    sys.exit(load_entry_point('sshuttle==1.0.5', 'console_scripts', 'sshuttle')())
  File "/home/linuxbrew/.linuxbrew/Cellar/sshuttle/1.0.5/libexec/lib/python3.9/site-packages/sshuttle/cmdline.py", line 46, in main
    return firewall.main(opt.method, opt.syslog)
  File "/home/linuxbrew/.linuxbrew/Cellar/sshuttle/1.0.5/libexec/lib/python3.9/site-packages/sshuttle/firewall.py", line 102, in main
    stdin, stdout = setup_daemon()
  File "/home/linuxbrew/.linuxbrew/Cellar/sshuttle/1.0.5/libexec/lib/python3.9/site-packages/sshuttle/firewall.py", line 73, in setup_daemon
    os.setsid()
PermissionError: [Errno 1] Operation not permitted
c : fatal: ['/bin/sudo', '-p', '[local sudo] Password: ', '/usr/bin/env', 'PYTHONPATH=/home/linuxbrew/.linuxbrew/Cellar/sshuttle/1.0.5/libexec/lib/python3.9/site-packages', '/home/linuxbrew/.linuxbrew/Cellar/sshuttle/1.0.5/libexec/bin/python', '/home/linuxbrew/.linuxbrew/bin/sshuttle', '-v', '-v', '-v', '--method', 'auto', '--firewall'] returned 1
```
(removing line generated via `sshuttle --sudoers-no-modify` from `sudoers` file didn't change the result)

**Comment by yermulnik** [comment]
The `Operation not permitted` looks to be tied to `os.setsid()` call but I haven't faced this kind of issues with `sshuttle` ever before and have no clue how to fix (meanwhile I have to run `sshuttle` via `sudo` which is a bit so-so).

**Comment by skuhl** [comment]
So, this is a problem that only occurs when you try to use the sudoers file? The current implementation of the --sudoers isn't great. See issue #631. I'm still not sure what exactly the problem is here though. I don't use the --sudoers option.

Looking at the code, setsid() does get called regardless of if daemon mode is used or not. I was confusing client.py and firewall.py.

**Comment by yermulnik** [comment]
> So, this is a problem that only occurs when you try to use the sudoers file?

Nope. I meant that problem occurs with and w/o sudoers entry.

**Comment by skuhl** [comment]
Do you have use_pty set in /etc/sudoers? That is the only way I can reproduce the issue. I haven't noticed Ubuntu enabling this setting. Maybe you enabled it or are using some flavor of Ubuntu that does? I think this should be straightforward to fix. I'll take a closer look when I get a chance.

**Comment by yermulnik** [comment]
@skuhl Yay! :partying_face: THANK YOU! :bow: The `use_pty` was the culprit.
Maybe it's worth adding this to README for those poor guys like me :smile:

**Comment by yermulnik** [comment]
Forgotten to mention: I'm on a loaner laptop with Ubuntu 20.04 which was installed by my Org's Corp IT and TBH I have no idea whether it's by default in `/etc/sudoers` in Ubuntu 20.04 or something that they added on their own.

**Comment by quickfur** [comment]
Ran into this same problem this week, and found this issue via Google.  Apparently Debian's sudo apparently now defaults to use_pty; it would be nice to have a real fix for this in sshuttle.

**Comment by skuhl** [comment]
It isn't clear to me why this call to setsid() is being used when sshuttle isn't run in daemon mode. My quick patch above was intended to just add a helpful error message and I didn't spent time trying to figure out how to fix it. 

The comment above the setsid() call implies that it might be used so that sshuttle doesn't die when Ctrl+C is pressed, but I believe the code just above that performs that task (ignore the SIGINT signal). I don't have use_pty set, but a few minutes of testing just now seems to show that removing that setsid() call didn't obviously break anything when running sshuttle normally or with the -D option.

This is the commit that added the setsid() call:
https://github.com/sshuttle/sshuttle/commit/a21e8c7a3c64ced07cc9f8895aa92d8e4cc976ef

**Comment by quickfur** [comment]
Does it do anything different with/without setsid() if you interrupt sshuttle with ctrl-C?  If not, then perhaps it's OK to just remove it?

**Comment by yermulnik** [comment]
For what it's worth: I, as a usual user, run `sshuttle` on Linux on an on-demand basis (mostly ad-hoc only to relay access to remote "grey" network via the ssh bastion host) and w/o `daemon`izing it. So doing `Ctrl-C` is somewhat a regular way for me to stop `sshuttle` and hence stop proxy'ing access along with all the clean up done by `sshuttle` during termination. There may be a lot of use cases where running `sshuttle` as a daemon is a requirement though. Thus I'd be looking forward for making `setsid()` an option rater than a "always on" thing.

For the sake of equity I must admit that when I was using Macbook Pro `sshuttle` was going into a background even despite me not passing it the `-D, --daemon` option. I have no clue why and I have no MacOS to re-verify or test anymore.

JFYI.

**Comment by skuhl** [comment]
There are two setsid() calls in sshuttle's code. The one in client.py should only get called when running as a daemon. The one in firewall.py gets called regardless of how sshuttle is run. That is the one causing the trouble and the one that I added the error message to in git.

> Does it do anything different with/without setsid() if you interrupt sshuttle with ctrl-C? If not, then perhaps it's OK to just remove it?

Removing setsid() didn't appear break things when use_pty is turned off (as I reported above)---but I didn't look at it carefully. Nonetheless, if I enable use_pty and remove the setsid() call to make sshuttle run, then the console output is garbled and Ctrl+C doesn't kill sshuttle. I believe I discovered this when I authored the pull request above, but I haven't had time to investigate.

**Comment by quickfur** [comment]
Someone suggested in the corresponding Debian bug report to make sshuttle invoke ssh with the `-T` option to suppress the allocation of a pseudo pty.  Perhaps this might be another way of fixing this issue?

**Comment by skuhl** [comment]
Do you have a link to the debian bug? I looked at this more closely today and think that I might have a fix. As far as I know, the problem is not related to the pseudo pty that SSH makes. 

One problem is that use_pty changes where signals go when you press Ctrl+C (sshuttle spawns off a separate process to manage the firewall with elevated privileges...there is more than one process to handle). Another issue is that use_pty garbles the console output of any other processes writing to the terminal besides the one running in sudo (missing carriage return). Both the non-sudo process and the sudo process in sshuttle print to the console simultaneously with the -v. The best that I can tell, both of these things are apparently things that happen with use_pty.

I still need to clean up my work and do some more testing on different configurations before posting a pull request. Maybe in the next week-ish.

**Comment by quickfur** [comment]
> Do you have a link to the debian bug?

Here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1003154
