### ISSUE TITLE
sshuttle-1.1.0: ipv6 configuration applied even if SO have modules not loaded

### ISSUE THREAD

**Issue by samuelbernardo** [sshuttle/sshuttle#738]
I catch the following issue using Archlinux after upgrade to sshuttle 1.1.0:
- ipv6 disabled
- sshuttle is loading ::1 as one of the rules and then it exits because can not bind to that address

To solve this issue, the option --disable-ipv6 needs to be set in the arguments or else it will fail to start.

Would be expected that, if ipv6 is not available locally, that sshuttle only starts the required configurations for ipv4.

**Comment by skuhl** [comment]
I believe pull request #728 should improve the situation for the next release. When the IPv6 bind fails, the new message indicates to the user that they might want to use --disable-ipv6. There may be some automatic way to handle this situation better. Nonetheless, I think the improved error message will at least reduce confusion about it.

If I recall correctly, a similar workaround to specify the --listen addresses that you want to use. If the method you are using supports IPv6, the listen address defaults to both ::1 and 127.0.0.1. New people are encountering this issue because IPv6 support was added to the iptables/nat method (which is the default on Linux). Previous to 1.1.0, sshuttle only supported IPv4 with the iptables/nat method.

**Comment by brianmay** [comment]
I believe this can be closed now #728 was merged.
