### ISSUE TITLE
sshuttle crashes if resolvectl exists but resolved not used

### ISSUE THREAD

**Issue by creshal** [sshuttle/sshuttle#790]
As long as a file called `resolvectl` exists in `$PATH`, sshuttle assumes that resolved is actively used, and crashes if it isn't:

```
Failed to flush caches: Unit dbus-org.freedesktop.resolve1.service not found.
fw: Received non-zero return code 1 when flushing DNS resolver cache.
client_loop: send disconnect: Broken pipe
```

Which isn't surprising, since:

```
> systemctl status systemd-resolved.service 
○ systemd-resolved.service - Network Name Resolution
     Loaded: loaded (/usr/lib/systemd/system/systemd-resolved.service; disabled; preset: enabled)
     Active: inactive (dead)
```

Since `resolvectl` is owned by the systemd package itself for Arch (and presumably other distributions), I can't remove it from `$PATH`.

**Comment by skuhl** [comment]
flush_systemd_dns_cache() in firewall.py tries to run the resolvectl command. However, it just prints the message if it failed. It does not include code to cause sshuttle to exit. Nonetheless, there very well could be some issue that is causing it to exit. I think I wrote the code initially and intended to have it work in the situation you are describing.  Just because the command exists, it doesn't mean that we should expect that resolved is running or expect our request to flush the cache is guaranteed to succeed.

**Comment by creshal** [comment]
My bad, I was trying to route 0/0 through a server without excluding it. But this was the only error message that sshuttle threw.
